title: RedCup
description: "Redcup: An awesome Theme for Jekyll"

url: http://iamnii.github.io/redcup/
port: 3000
highlighter: pygments

permalink: /:year/:month/:day/:title.html
markdown: redcarpet

google_analytics: #

owner:
  name: Adjetey Sowah
  disqus_shortname: iamnii
  twitter: __iamnii
